### ISSUE TITLE
AS parser too optimistic?

### ISSUE THREAD

**Issue by nor3th** [fhightower/ioc-finder#136]
hey

I am currently using ioc-finder for parsing PDF reports and I am not sure if the AS parser might be a bit too optimistic, since it is also interprets the following sentence as a mention of an AS.

```
ioc_finder.parse_asns("today the same thing happened as 2014. I can't believe it!")
-> ['ASN2014']
```
Are there that many AS mentions in this format or might the current detection rule create more false positive than true positives?

**OS**

OS: ubuntu 20.04
Python:  3.9
ioc-finder: 6.0.0

**Comment by fhightower** [comment]
Hi @nor3th! Thanks for reporting this. I'll give the matter some thought. I have seen instances where ASNs are written as `AS 1234`, but we certainly don't want to capture false positives. At the very least, I will update the grammar so that it will only match on capital `AS`. So it would match `... AS 2014...` but not `... as 2014...`. Even with this strategy, there is still the possibility of creating false positives, but it is less likely. Any thoughts on this approach?

**Comment by nor3th** [comment]
Hey, I was also thinking that dropping the detection for "as 2014" while still keeping "AS 2014" might be the way to go. Technically the latter would still throw false positives if the text is written in all capital letters, but that way of writing is more out of the ordinary.

I'll let you know if I can think of another/better approach, but for now the mentioned one might be the best option.

**Comment by fhightower** [comment]
Perfect. I've pushed a new version (`v6.0.1`) improving the ASN grammar to reduce these false positives. I'm going to close this ticket for now, but feel free to re-open or comment if you have any other ideas/input. Thanks again for raising this issue!
