### ISSUE TITLE
Email authentication fields included in parsed email address

### ISSUE THREAD

**Issue by wesinator** [fhightower/ioc-finder#16]
`smtp.mailfrom=example@example.com`
whole string is parsed as email

**Expected**: `example@example.com`

**Comment by fhightower** [comment]
@wesinator , thanks for reporting this. The package is working as expected.  Email addresses can contain the `=` character (https://en.wikipedia.org/wiki/Email_address#Local-part).

Your expectation is reasonable, though, and there is a "simple_email_addresses" key available in the json response provided by this package which provides email addresses parsed as we normally expect them to be. You can see the difference between the "email_addresses" and "simple_email_addresses" keys here: https://github.com/fhightower/ioc-finder/blob/master/tests/test_edge_cases.py#L151 .

**Comment by fhightower** [comment]
On second thought, I've updated this package so that the email address you expected to find is outputed as the `email_addresses` key and emails closer to the full spec are outputed at the  `complete_email_addresses` key. You can read more about this here: https://github.com/fhightower/ioc-finder#output-details .
