### ISSUE TITLE
Email parsing - match email addresses containing backslash escapes ?

### ISSUE THREAD

**Issue by wesinator** [fhightower/ioc-finder#78]
I've seen a few real cases of DNS SOA field emails containing backslash escapes - https://securitytrails.com/domain/siemensdungs.com/history/soa 
`hwclouds\\@cs.huawei.com`

The raw DNS response (which has changed) had a single slash `hwclouds\@cs.huawei.com` (probably an escape for the `@`)

[According](https://stackoverflow.com/questions/2049502/what-characters-are-allowed-in-an-email-address) to RFC , it seems technically email addresses can have a char escaped by preceding `\` 
see https://tools.ietf.org/html/rfc3696#section-3 for valid examples

 ioc-finder does not currently match this email address:
```python
import ioc_finder
print(ioc_finder.__version__)
soa = "hwclouds\@cs.huawei.com"
print(soa)
ioc_finder.find_iocs(soa)
```

**Comment by fhightower** [comment]
Hey @wesinator, thanks for raising this issue! That link to the RFC was helpful; the IOC finder package currently is not parsing email addresses like `abc\@def@example.com` properly and I'll get that updated.

However, I'm confused about your example. Based on [https://tools.ietf.org/html/rfc3696#section-3](https://tools.ietf.org/html/rfc3696#section-3), I understand `\` to be a quoting character, basically escaping the next character so that it is not processed as a control character (hence given `abc\@def@example.com`, `abc\@def` is the local part and `example.com` is the domain part. If this is correct, I don't think your example is a valid email address; considering `hwclouds\@cs.huawei.com`, the `\@` means that the `@` character will not be processed as control character. But there is not other `@` character to seperate the local part from the domain part (which means that it is not a valid email address). If it were `hwclouds\@foo@cs.huawei.com`, that would make sense, but I don't think the example you posted is valid. Perhaps they are defanging it (maybe the real SOA email is `hwclouds@cs.huawei.com`)?

**Comment by wesinator** [comment]
Maybe - that was the raw example so I don't know exactly what it was. 
The actual email could also have been `hwclouds\@cs@huawei.com` 

Since there is technically no way to tell exactly where the `@` is supposed to be in a SOA rname, it is done best-guess - my library https://github.com/wesinator/soaparse has the best guess algorithms for getting the email address.

**Comment by fhightower** [comment]
Ok, thanks for the info. I'll update the package to accurately handle email addresses like `abc\@def@example.com`.
